#!/usr/bin/env python3
"""Build a single wide LaTeX table from ebm_graph_fusion_metrics/**/ebm_graph_fusion_test_metrics.csv."""

from __future__ import annotations

import argparse
from pathlib import Path

import pandas as pd


def _repo_root() -> Path:
    return Path(__file__).resolve().parent.parent


def _fmt_mse(x: float | None) -> str:
    if x is None or (isinstance(x, float) and pd.isna(x)):
        return "---"
    return f"{float(x):.4f}"


def _escape_dataset(name: str) -> str:
    return str(name).replace("_", "\\_")


def build_tex(
    df: pd.DataFrame,
    coverages: list[float],
) -> str:
    """df: test split rows with columns dataset, model, method, target_coverage, split_mse_selected."""
    method_order = ["ebm_only", "graph_only", "fusion"]
    method_labels = ["TEM", "Graph", "Fusion"]

    datasets = sorted(df["dataset"].unique())
    # Prefer ETT / electricity / traffic / weather order
    preferred = ["ETTh1", "ETTh2", "ETTm1", "ETTm2", "electricity", "traffic", "weather"]
    datasets = [d for d in preferred if d in set(datasets)] + [
        d for d in datasets if d not in preferred
    ]

    models = sorted(df["model"].unique())

    # Lookup: (dataset, model, method, rho) -> mse
    L: dict[tuple[str, str, str, float], float] = {}
    for r in df.itertuples(index=False):
        tc = float(r.target_coverage)
        if tc not in coverages:
            continue
        key = (str(r.dataset), str(r.model), str(r.method), tc)
        L[key] = float(r.split_mse_selected)

    n_cov = len(coverages)
    n_sub = len(method_order)
    col_spec = "ll" + "r" * (n_cov * n_sub)

    lines: list[str] = [
        "% Auto-generated by scripts/export_ebm_graph_fusion_unified_table.py",
        "% Test split: selective MSE (lower is better). TEM = ebm_only, Graph = graph_only, Fusion = fusion.",
        "% Preamble: \\usepackage{booktabs,graphicx}",
        "\\begin{table*}[t]",
        "\\centering",
        "\\caption{Test selective prediction MSE across datasets and backbones. "
        "Columns group target coverage $\\rho$; within each $\\rho$ we report TEM, graph energy, and fused energy (lower is better).}",
        "\\label{tab:ebm_graph_fusion_unified}",
        "\\resizebox{\\textwidth}{!}{%",
        f"\\begin{{tabular}}{{{col_spec}}}",
        "\\toprule",
    ]

    # Header row 1: rho groups
    head1 = ["Dataset", "Backbone"]
    for c in coverages:
        head1.append(f"\\multicolumn{{{n_sub}}}{{c}}{{$\\rho={c}$}}")
    lines.append(" & ".join(head1) + " \\\\")

    # cmidrules
    for i, _ in enumerate(coverages):
        lo = 2 + i * n_sub + 1
        hi = lo + n_sub - 1
        lines.append(f"\\cmidrule(lr){{{lo}-{hi}}}")

    # Header row 2: TEM / Graph / Fusion repeated
    head2 = ["", ""]
    for _ in coverages:
        head2.extend(method_labels)
    lines.append(" & ".join(head2) + " \\\\")
    lines.append("\\midrule")

    dataset_blocks: list[list[str]] = []
    for ds in datasets:
        block_lines: list[str] = []
        first_in_ds = True
        for model in models:
            row_has_any = any(
                (ds, model, m, tc) in L
                for m in method_order
                for tc in coverages
            )
            if not row_has_any:
                continue

            ds_cell = _escape_dataset(ds) if first_in_ds else ""
            first_in_ds = False
            cells = [ds_cell, model]
            for tc in coverages:
                for m in method_order:
                    cells.append(_fmt_mse(L.get((ds, model, m, tc))))
            block_lines.append(" & ".join(cells) + " \\\\")
        if block_lines:
            dataset_blocks.append(block_lines)

    for bi, block in enumerate(dataset_blocks):
        lines.extend(block)
        if bi < len(dataset_blocks) - 1:
            lines.append("\\addlinespace[0.3em]")

    lines.append("\\bottomrule")
    lines.append("\\end{tabular}")
    lines.append("}")
    lines.append("\\end{table*}")
    lines.append("")
    return "\n".join(lines)


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument(
        "--metrics-root",
        type=Path,
        default=_repo_root() / "ebm_graph_fusion_metrics",
        help="Directory containing <model>/ebm_graph_fusion_test_metrics.csv",
    )
    ap.add_argument(
        "-o",
        "--output",
        type=Path,
        default=_repo_root() / "docs" / "ebm_graph_fusion_paper_table.tex",
    )
    ap.add_argument(
        "--coverages",
        type=float,
        nargs="+",
        default=[0.5, 0.6, 0.7, 0.8, 0.9],
        help="Target coverage levels (columns)",
    )
    args = ap.parse_args()

    paths = sorted(args.metrics_root.glob("*/ebm_graph_fusion_test_metrics.csv"))
    if not paths:
        raise SystemExit(f"No test metrics CSV under {args.metrics_root}")

    dfs = [pd.read_csv(p) for p in paths]
    df = pd.concat(dfs, ignore_index=True)
    df = df[df["split"] == "test"].copy()

    tex = build_tex(df, args.coverages)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(tex, encoding="utf-8")
    print(f"Wrote {args.output} ({len(df)} rows from {len(paths)} files)")


if __name__ == "__main__":
    main()
