#!/usr/bin/env python3
"""Generate a LaTeX table: full-split test MSE without selective inference (split_mse_orig).

Reads ebm_graph_fusion_*_metrics.csv produced by compare_ebm_graph_fusion.py. For each
dataset and backbone, split_mse_orig is the MSE over all test samples (no energy gate).
One row per (dataset, model) is taken from method=ebm_only (values match across methods).
"""

from __future__ import annotations

import argparse
import csv
from pathlib import Path


def _repo_root() -> Path:
    return Path(__file__).resolve().parent.parent


def _fmt(x: float | None) -> str:
    if x is None:
        return "---"
    return f"{float(x):.4f}"


def _load_orig_mse(
    rows: list[dict], *, split: str, method: str
) -> dict[tuple[str, str], float]:
    """(dataset, model) -> split_mse_orig."""
    out: dict[tuple[str, str], float] = {}
    for r in rows:
        if r.get("split") != split or r.get("method") != method:
            continue
        ds = str(r["dataset"])
        m = str(r["model"])
        key = (ds, m)
        if key in out:
            continue
        out[key] = float(r["split_mse_orig"])
    return out


def build_tex(
    L: dict[tuple[str, str], float],
    datasets: list[str],
    models: list[str],
    *,
    split: str,
) -> str:
    if split == "test":
        cap = "Full-split MSE without selective inference on the test set (lower is better)."
    else:
        cap = (
            f"Full-split MSE without selective inference on the {split} split "
            "(lower is better)."
        )
    lines: list[str] = [
        "% Auto-generated by scripts/export_backbone_full_mse_latex.py",
        "% MSE = split_mse_orig: MSE over all samples in the split (no energy-based selection).",
        "% Preamble: \\usepackage{booktabs,graphicx}",
        "\\begin{table*}[t]",
        "\\centering",
        "\\caption{" + cap + "}",
        "\\label{tab:backbone_full_mse}",
        "\\resizebox{\\textwidth}{!}{%",
        "\\begin{tabular}{l" + "r" * len(models) + "}",
        "\\toprule",
        "Dataset & " + " & ".join(models) + " \\\\",
        "\\midrule",
    ]
    for ds in datasets:
        row = [ds.replace("_", "\\_")]
        for m in models:
            row.append(_fmt(L.get((ds, m))))
        lines.append(" & ".join(row) + " \\\\")
    lines.append("\\bottomrule")
    lines.append("\\end{tabular}")
    lines.append("}")
    lines.append("\\end{table*}")
    lines.append("")
    return "\n".join(lines)


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument(
        "--csv",
        type=Path,
        default=_repo_root() / "ebm_graph_fusion_test_metrics.csv",
        help="Input CSV (test metrics)",
    )
    ap.add_argument(
        "-o",
        "--output",
        type=Path,
        default=_repo_root() / "docs" / "ebm_graph_backbone_full_mse_test.tex",
    )
    ap.add_argument(
        "--split",
        default="test",
        help="Which split column value to use",
    )
    ap.add_argument(
        "--method",
        default="ebm_only",
        help="Which method row to read split_mse_orig from (same for all methods)",
    )
    args = ap.parse_args()

    with open(args.csv, newline="", encoding="utf-8") as f:
        rows = list(csv.DictReader(f))

    L = _load_orig_mse(rows, split=args.split, method=args.method)

    preferred = [
        "ETTh1",
        "ETTh2",
        "ETTm1",
        "ETTm2",
        "electricity",
        "traffic",
        "weather",
    ]
    all_ds = sorted({k[0] for k in L})
    datasets = [d for d in preferred if d in set(all_ds)] + [
        d for d in all_ds if d not in preferred
    ]

    models = sorted({k[1] for k in L})

    tex = build_tex(L, datasets, models, split=args.split)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(tex, encoding="utf-8")
    print(f"Wrote {args.output} ({len(L)} cells)")


if __name__ == "__main__":
    main()
