#!/usr/bin/env python3
"""Generate LaTeX tables (TEM vs graph, test MSE) from ebm_graph_fusion_test_metrics.csv."""

from __future__ import annotations

import argparse
import csv
from pathlib import Path


def _repo_root() -> Path:
    return Path(__file__).resolve().parent.parent


def _fmt(x: float | None) -> str:
    if x is None:
        return "---"
    return f"{x:.4f}"


def build_tex(rows: list[dict], coverages: list[float]) -> str:
    methods = {"ebm_only": "TEM", "graph_only": "Graph"}
    L: dict[tuple[str, str, str, float], float] = {}
    for r in rows:
        if r["method"] not in methods:
            continue
        tc = float(r["target_coverage"])
        if tc not in coverages:
            continue
        key = (r["dataset"], r["model"], r["method"], tc)
        L[key] = float(r["split_mse_selected"])

    datasets = sorted(set(r["dataset"] for r in rows))
    models = sorted(set(r["model"] for r in rows))

    lines: list[str] = [
        "% Auto-generated by scripts/export_ebm_graph_tem_vs_graph_latex.py",
        "% TEM = ebm_only, Graph = graph_only. "
        '"---" = missing row in CSV (no test samples under val-derived threshold).',
        "% Preamble: \\usepackage{booktabs,graphicx}",
    ]

    for model in models:
        lines.append("\\begin{table*}[t]")
        lines.append("\\centering")
        covs_tex = ",".join(str(c) for c in coverages)
        lines.append(
            "\\caption{Test selective MSE (lower is better): TEM vs.\\ graph energy at "
            f"target coverages $\\rho \\in \\{{{covs_tex}\\}}$. "
            "Backbone: " + model + ".}"
        )
        lines.append("\\label{tab:tem_graph_" + model.replace(" ", "") + "}")
        lines.append("\\resizebox{\\textwidth}{!}{%")
        lines.append("\\begin{tabular}{l" + "r" * (2 * len(coverages)) + "}")
        lines.append("\\toprule")
        rho_headers = " & ".join(
            f"\\multicolumn{{2}}{{c}}{{$\\rho={c}$}}" for c in coverages
        )
        lines.append(f" & {rho_headers} \\\\")
        for i, c in enumerate(coverages):
            lo = 2 + 2 * i
            hi = lo + 1
            lines.append(f"\\cmidrule(lr){{{lo}-{hi}}}")
        lines.append("Dataset & " + " & ".join(["TEM & Graph"] * len(coverages)) + " \\\\")
        lines.append("\\midrule")
        for ds in datasets:
            cells = [ds.replace("_", "\\_")]
            for cov in coverages:
                e = L.get((ds, model, "ebm_only", cov))
                g = L.get((ds, model, "graph_only", cov))
                cells.append(_fmt(e))
                cells.append(_fmt(g))
            lines.append(" & ".join(cells) + " \\\\")
        lines.append("\\bottomrule")
        lines.append("\\end{tabular}")
        lines.append("}")
        lines.append("\\end{table*}")
        lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument(
        "--csv",
        type=Path,
        default=_repo_root() / "ebm_graph_fusion_test_metrics.csv",
        help="Input CSV from compare_ebm_graph_fusion.py",
    )
    ap.add_argument(
        "-o",
        "--output",
        type=Path,
        default=_repo_root() / "docs" / "ebm_graph_tem_vs_graph_test_tables.tex",
    )
    ap.add_argument(
        "--coverages",
        type=float,
        nargs="+",
        default=[0.5, 0.7, 0.9],
        help="Target coverage levels to include",
    )
    args = ap.parse_args()

    with open(args.csv, newline="", encoding="utf-8") as f:
        rows = list(csv.DictReader(f))

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(build_tex(rows, args.coverages), encoding="utf-8")
    print(f"Wrote {args.output}")


if __name__ == "__main__":
    main()
